### ISSUE TITLE
Join forces with https://github.com/janet-lang/jhydro?

### ISSUE THREAD

**Issue by andrewchambers** [joy-framework/cipher#1]
Don't know if you had not seen this, or specifically avoided it. Feel free to close this issue.

**Comment by pepe** [comment]
It was debated on gitter I think, that the purpose is a little bit different. Still, after some playground with jhydro, I would vote for merging these two. Less C code is better :-). Also, cipher can stay, just use the jhydro lib.

**Comment by swlkr** [comment]
Yeah definitely going to ditch my custom c and use jhydro underneath

**Comment by swlkr** [comment]
Closed 58fbe201a3d7471e3491b2a0452a9631ac637998
