### ISSUE TITLE
Forked jyhdro does not build

### ISSUE THREAD

**Issue by LeviSchuck** [joy-framework/cipher#3]
The janet lang jyhdro repo has this commit.
https://github.com/janet-lang/jhydro/commit/180ccdd11559ffac2dadfb8c28ffb8f72c7f7de3

While this fork does not and will not build with the following message.

```
compiling jhydro.c to build/jhydro.o...
jhydro.c:81:36: error: implicitly declaring library function 'floor' with type 'double (double)'
      [-Werror,-Wimplicit-function-declaration]
    if (d < 0 || d > UINT32_MAX || floor(d) != d) {
                                   ^
jhydro.c:81:36: note: include the header <math.h> or explicitly provide a declaration for 'floor'
1 error generated.
```

Is there a reason to stick with the fork?

**Comment by swlkr** [comment]
There's no reason, the fork's one commit was merged a while ago, totally forgot to push this commit

4f7d252063c14a46f271891f262e0f4496e62e2b
